spring:
  application:
    name: registration-service

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

keycloak:
  realm: ${REALM}
  server-url: ${KEYCLOAK_SERVER_URL}
  admin-client-id: ${ADMIN_CLIENT_ID}
  admin-client-secret: ${ADMIN_CLIENT_SECRET}
  auth-client-id: ${AUTH_CLIENT_ID}
  auth-client-secret: ${AUTH_CLIENT_SECRET}

logging:
  config: classpath:logback.xml
