spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/passengers}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        batch_size: 50
        fetch_size: 50
        show_sql: true
        format_sql: true
        hdm2ddl:
          auto: validate
        check_nullability: true
    open-in-view: false
  liquibase:
    change-log: db/changelog/db.changelog-master.xml