spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: driver
          uri: lb://driver
          predicates:
            - Path=${commonApiPath}/cars/**, ${commonApiPath}/drivers/**

        - id: passenger
          uri: lb://passenger
          predicates:
            - Path=${commonApiPath}/passengers/**

        - id: rating
          uri: lb://rating
          predicates:
            - Path=${commonApiPath}/rates/**

        - id: ride
          uri: lb://ride
          predicates:
            - Path=${commonApiPath}/rides/**

        - id: registration-service
          uri: lb://registration-service
          predicates:
            - Path=${commonApiPath}/taxi/**

commonApiPath: /api/v1
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}