version: '3.8'

services:
  rating-db:
    image: postgres:15-alpine
    container_name: rating
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rating
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    ports:
      - "5433:5432"
    volumes:
      - rating_data:/var/lib/postgresql/data

  rides-db:
    image: postgres:15-alpine
    container_name: rides
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rides
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    ports:
      - "5434:5432"
    volumes:
      - rides_data:/var/lib/postgresql/data

volumes:
  rating_data:
  rides_data: