version: '3.8'

services:
  rating-db:
    image: postgres:15-alpine
    container_name: rating
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rating
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    ports:
      - "5433:5432"
    volumes:
      - rating_data:/var/lib/postgresql/data

  rides-db:
    image: postgres:15-alpine
    container_name: rides
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rides
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    ports:
      - "5434:5432"
    volumes:
      - rides_data:/var/lib/postgresql/data

  passengers-db:
    image: postgres:15-alpine
    container_name: passenger
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: passengers
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    ports:
      - "5435:5432"
    volumes:
      - passengers_data:/var/lib/postgresql/data

  drivers-db:
    image: postgres:15-alpine
    container_name: driver
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drivers
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    ports:
      - "5436:5432"
    volumes:
      - drivers_data:/var/lib/postgresql/data

volumes:
  rating_data:
  rides_data:
  passengers_data:
  drivers_data: