filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata: { }

filebeat.modules:
  - module: system
    syslog:
      enabled: true
      var.paths: ["/var/log/syslog*"]
  - module: system
    auth:
      enabled: true
      var.paths: ["/var/log/auth.log*"]
setup.kibana:
  host: "http://kibana:5601"
output.logstash:
  hosts: [ "logstash:5044" ]
