spring:
  application:
    name: driver
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5436/drivers}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        batch_size: 50
        fetch_size: 50
        show_sql: true
        format_sql: true
        hdm2ddl:
          auto: validate
        check_nullability: true
    open-in-view: false
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

server:
  port: 8081